open Utils

module G = (Screen)

let draw_asteroid b buf =
  let open Ball in
  let open Vector in
G.set_color (Color.rgb 104 104 104) buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 0) 2 2 buf;
G.set_color (Color.rgb 113 113 113) buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 12) 2 2 buf;
G.set_color (Color.rgb 135 135 135) buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 14) 2 2 buf;
G.set_color (Color.rgb 76 76 76) buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -18) 2 2 buf;
G.set_color (Color.rgb 119 119 119) buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 18) 2 2 buf;
G.set_color (Color.rgb 129 129 129) buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 20) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -24) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -24) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -24) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -24) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -24) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -22) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -22) 2 2 buf;
G.set_color (Color.rgb 115 115 115) buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 16) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) -20) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -18) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -16) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -28) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -28) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -28) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -28) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -28) 2 2 buf;
G.set_color (Color.rgb 91 91 91) buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 24) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 24) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 24) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 24) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 24) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 24) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) -10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 22) ((int b.pos.y) -12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 20) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -26) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -28) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -28) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -28) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -30) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -30) 2 2 buf;
G.fill_rect ((int b.pos.x) -6) ((int b.pos.y) -30) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -30) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -30) 2 2 buf;
G.set_color (Color.rgb 147 147 147) buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) + 18) ((int b.pos.y) + 10) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 16) ((int b.pos.y) + 8) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) + 6) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 2) ((int b.pos.y) + 0) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 14) ((int b.pos.y) -2) 2 2 buf;
G.fill_rect ((int b.pos.x) + 0) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -4) 2 2 buf;
G.fill_rect ((int b.pos.x) -2) ((int b.pos.y) -6) 2 2 buf;
G.fill_rect ((int b.pos.x) -4) ((int b.pos.y) -8) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) -8) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) -24) 2 2 buf;
G.fill_rect ((int b.pos.x) -12) ((int b.pos.y) -26) 2 2 buf;
G.set_color (Color.rgb 82 82 82) buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -14) 2 2 buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 12) ((int b.pos.y) -16) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -18) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 8) ((int b.pos.y) -20) 2 2 buf;
G.fill_rect ((int b.pos.x) + 4) ((int b.pos.y) -22) 2 2 buf;
G.fill_rect ((int b.pos.x) + 6) ((int b.pos.y) -22) 2 2 buf;
G.set_color (Color.rgb 131 131 131) buf;
G.fill_rect ((int b.pos.x) + 10) ((int b.pos.y) + 20) 2 2 buf;
G.fill_rect ((int b.pos.x) -10) ((int b.pos.y) + 12) 2 2 buf;
G.fill_rect ((int b.pos.x) -14) ((int b.pos.y) + 8) 2 2 buf;
